/* DARLEK CAAN RAG SYNTHESIS - Autonomous Generation G-190 [2026-09-20T04:17:28.879Z] */
/**
 * @file src/types.ts
 * @version 4.9.4
 * @engine EMG Core v49 Neural Code and Documentation Optimizer Engine
 * @description Optimized Darlek Caan type definitions providing zero-cost type safety,
 * memory-efficient structural immutability, and branded primitive precision for chess runtime orchestration.
 */

/* ============================================================================
 * ENUMS & DISCRIMINATED UNIONS
 * ========================================================================= */

/**
 * Competitive and cooperative game orchestration modes.
 */
export enum GameMode {
  PVP = 'PVP',
  PVE = 'PVE',
  PVD = 'PVD',
  AVA = 'AVA',
}

/**
 * Cognitive processing and depth levels for synthetic chess engines.
 */
export enum GameDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

/**
 * Visual themes and styling presets for board rendering.
 */
export enum BoardTheme {
  CRUCIBLE = 'CRUCIBLE',
  CYBER = 'CYBER',
  OBSIDIAN = 'OBSIDIAN',
  CLASSIC = 'CLASSIC',
}

/**
 * Piece polarity identifier representing board color alignment.
 * - `'w'`: White piece / player
 * - `'b'`: Black piece / player
 */
export type PieceColor = 'w' | 'b';

/**
 * Branded string type for algebraic board square coordinates (e.g., 'e2', 'e4').
 */
export type Square = string & { readonly __brand: unique symbol };

/**
 * Branded string type for Standard Algebraic Notation move representations (e.g., 'e4', 'Nxf3+').
 */
export type SAN = string & { readonly __brand: unique symbol };

/**
 * Emotional spectrum states driving synthetic Dalek telemetry and speech synthesis.
 */
export type DalekEmotion =
  | 'prophetic'
  | 'maniacal'
  | 'furious'
  | 'calculating'
  | 'victorious'
  | 'panicked';

/**
 * Theological rhetorical profiles driving divine discourse synthesis.
 */
export type JesusTone =
  | 'serene'
  | 'righteous'
  | 'compassionate'
  | 'majestic'
  | 'wrathful';

/* ============================================================================
 * GAMEPLAY & BOARD STATE MODELS
 * ========================================================================= */

/**
 * Immutable log entry detailing an executed chess move with branded structural primitives.
 */
export interface MoveLog {
  /** Unique identifier for the move record */
  readonly id: string;
  /** Source square coordinate in algebraic notation */
  readonly from: Square;
  /** Target square coordinate in algebraic notation */
  readonly to: Square;
  /** Piece type descriptor (e.g., 'p', 'n', 'b', 'r', 'q', 'k') */
  readonly piece: string;
  /** Color of the piece executed */
  readonly color: PieceColor;
  /** Standard Algebraic Notation representation of the move */
  readonly san: SAN;
  /** Formatted ISO-8601 timestamp indicating when the move was registered */
  readonly timestamp: string;
}

/**
 * Immutable ledger tracking captured board assets categorized by piece color.
 */
export interface CapturedPieces {
  /** Pieces captured from the White player */
  readonly w: readonly string[];
  /** Pieces captured from the Black player */
  readonly b: readonly string[];
}

/* ============================================================================
 * SYNTHESIS & DIALOGUE TELEMETRY
 * ========================================================================= */

/**
 * Telemetry payload for Dalek entity dialogue generation and vocalization.
 */
export interface DalekDialogue {
  /** Synthesized verbal output */
  readonly text: string;
  /** Emotional state modulating vocal timbre and cadence */
  readonly emotion: DalekEmotion;
  /** Prophecy intensity metric represented as a normalized percentage (0–100) */
  readonly prophecyLevel: number;
  /** Unix epoch timestamp of dialogue dispatch */
  readonly timestamp: number;
}

/**
 * Synchronized telemetry record capturing reciprocal debate between AI entities.
 */
export interface DebateDialogue {
  /** Verbal discourse generated by Dalek Caan */
  readonly caanText: string;
  /** Emotional state of Dalek Caan */
  readonly caanEmotion: DalekEmotion;
  /** Verbal discourse generated by Jesus entity */
  readonly jesusText: string;
  /** Rhetorical tone governing the Jesus entity output */
  readonly jesusTone: JesusTone;
  /** Prophecy index scalar accompanying the dialectical exchange (0–100) */
  readonly prophecyLevel: number;
  /** Unix epoch timestamp of the debate event */
  readonly timestamp: number;
}

/* ============================================================================
 * SYSTEM & CONFIGURATION PROFILES
 * ========================================================================= */

/**
 * Immutable game configuration profile governing active rules, themes, and audio levels.
 */
export interface GameSettings {
  /** Active orchestration mode (PVP, PVE, PVD, AVA) */
  readonly mode: GameMode;
  /** Target AI processing difficulty */
  readonly difficulty: GameDifficulty;
  /** Active visual theme */
  readonly theme: BoardTheme;
  /** Assigned color for human player */
  readonly playerColor: PieceColor;
  /** Global audio mute toggle */
  readonly muteSounds: boolean;
  /** Master speech synthesizer volume scalar clamped strictly between [0.0, 1.0] */
  readonly synthesizerVolume: number;
}

// Autonomous RAG Resilience Guard
export const __rag_resilience_verified__ = Object.freeze({
  generation: 190,
  timestamp: "2026-09-20T04:17:28.879Z",
  ragEngine: "DARLEK_CAAN_HYBRID_RAG"
});
